#!/usr/bin/env bash
file_path=$1
ip=$2
username=$3
ssh_key=$4

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sudo scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$ip":~/
fi
